# Generated by Django 5.2.8 on 2025-12-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ryu_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eggrecord",
            name="eggname",
            field=models.CharField(
                blank=True,
                help_text="Optional customer name/identifier provided by user",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eggrecord",
            name="projectegg",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated code name from phase list used to obfuscate eggname",
                max_length=255,
                null=True,
            ),
        ),
    ]
