# Generated by Django 4.2.27 on 2025-12-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ryu_app", "0002_add_eggname_projectegg_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculatedHeuristicsRule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rule_pattern", models.CharField(max_length=255)),
                ("nmap_arguments", models.JSONField(blank=True, null=True)),
                (
                    "recommended_technique",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "success_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("sample_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "calculated_heuristics_rules",
                "ordering": ["-confidence_score", "-sample_count"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IPTechniqueEffectiveness",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("asn", models.CharField(blank=True, max_length=50, null=True)),
                ("cidr_block", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "ipv6_prefix",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("waf_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "technique_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                (
                    "avg_scan_duration",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ip_technique_effectiveness",
                "ordering": ["-last_updated"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="KageScanResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("target", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "technique_used",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("waf_detected", models.BooleanField(blank=True, null=True)),
                ("waf_type", models.CharField(blank=True, max_length=255, null=True)),
                ("open_ports_found", models.IntegerField(blank=True, null=True)),
                ("bypass_successful", models.BooleanField(blank=True, null=True)),
                (
                    "scan_duration",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ash_scan_results",
                "ordering": ["-scanned_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="KageTechniqueEffectiveness",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "target_pattern",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("waf_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "technique_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                ("last_failure", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("technique_metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "ash_technique_effectiveness",
                "ordering": ["-last_updated"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="KageWAFDetection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("waf_type", models.CharField(blank=True, max_length=255, null=True)),
                ("bypass_successful", models.BooleanField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("detected_at", models.DateTimeField(blank=True, null=True)),
                ("target", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "ash_waf_detections",
                "ordering": ["-detected_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PostgresDNSQuery",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("query_type", models.CharField(max_length=10)),
                ("result", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "customer_eggs_eggrecords_general_models_dnsquery",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PostgresEggRecord",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "subDomain",
                    models.CharField(
                        blank=True, db_column="subDomain", max_length=255, null=True
                    ),
                ),
                ("domainname", models.CharField(blank=True, max_length=255, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("alive", models.BooleanField(default=True)),
                ("eggname", models.CharField(blank=True, max_length=255, null=True)),
                ("projectegg", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "customer_eggs_eggrecords_general_models_eggrecord",
                "ordering": ["-updated_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PostgresNmap",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("target", models.CharField(max_length=255)),
                ("scan_type", models.CharField(max_length=50)),
                ("open_ports", models.TextField(blank=True, null=True)),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("scan_status", models.CharField(default="completed", max_length=50)),
                ("port", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "customer_eggs_eggrecords_general_models_nmap",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PostgresRequestMetadata",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("url", models.URLField(max_length=2048)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "customer_eggs_eggrecords_general_models_requestmetadata",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TechnologyFingerprint",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "technology_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("product", models.CharField(blank=True, max_length=255, null=True)),
                ("version", models.CharField(blank=True, max_length=255, null=True)),
                ("target", models.CharField(blank=True, max_length=255, null=True)),
                ("detected_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "technology_fingerprints",
                "ordering": ["-detected_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WAFDetectionDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("waf_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "waf_version",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "waf_product",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("detected_at", models.DateTimeField(blank=True, null=True)),
                ("target", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "waf_detection_details",
                "ordering": ["-detected_at"],
                "managed": False,
            },
        ),
    ]
