# Generated by Django 4.2.27 on 2025-12-13 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ryu_app", "0003_calculatedheuristicsrule_iptechniqueeffectiveness_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordlistUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wordlist_name", models.CharField(db_index=True, max_length=255)),
                ("filename", models.CharField(max_length=255)),
                (
                    "cms_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("source", models.CharField(default="uploaded", max_length=50)),
                ("paths_count", models.IntegerField(default=0)),
                ("uploaded_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA256 hash of file content for deduplication",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wordlist_name", "created_at"],
                        name="ryu_app_wor_wordlis_25a130_idx",
                    ),
                    models.Index(
                        fields=["cms_name", "created_at"],
                        name="ryu_app_wor_cms_nam_7b4365_idx",
                    ),
                ],
            },
        ),
    ]
