#!/bin/bash
# Cloudflare Blocklist - Generated Rules
# Generated by EGO Revolution

# IPv6 Rules
ip6tables -A INPUT -s 2400:cb00::/32 -j DROP
ip6tables -A INPUT -s 2606:4700::/32 -j DROP
ip6tables -A INPUT -s 2803:f800::/32 -j DROP
ip6tables -A INPUT -s 2a06:98c0::/29 -j DROP
ip6tables -A INPUT -s 2c0f:f248::/32 -j DROP

# Note: IPv4 rules require ASN database
# Use ip_ownership_validator to generate IPv4 rules
