# Generated by Django 4.2.27 on 2025-12-15 06:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []
    
    # Run on eggrecords database (enrichment tables)
    def get_database_for_model(self, model_name):
        """Route enrichment system models to eggrecords database."""
        if model_name in ('TechnologyFingerprint', 'CVEFingerprintMatch'):
            return 'eggrecords'
        return None

    operations = [
        migrations.CreateModel(
            name="DNSAuthority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("record_id_id", models.UUIDField(db_index=True)),
                ("md5", models.CharField(max_length=255)),
                (
                    "A",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv4"
                    ),
                ),
                ("AAAA", models.CharField(default="", max_length=255)),
                ("NS", models.CharField(default="", max_length=255)),
                ("CNAME", models.CharField(default="", max_length=255)),
                ("r", models.CharField(default="", max_length=255)),
                ("MX", models.TextField(default="")),
                ("TXT", models.TextField(default="")),
                ("ANY", models.CharField(default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "DNS Authority",
                "verbose_name_plural": "DNS Authorities",
                "db_table": "customer_eggs_eggrecords_general_models_dnsauthority",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DNSQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("record_id_id", models.UUIDField(db_index=True)),
                ("md5", models.CharField(max_length=255)),
                (
                    "A",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv4"
                    ),
                ),
                ("AAAA", models.CharField(default="", max_length=255)),
                ("NS", models.TextField(default="")),
                ("CNAME", models.TextField(default="")),
                ("r", models.TextField(default="")),
                ("MX", models.TextField(default="")),
                ("TXT", models.TextField(default="")),
                ("ANY", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "DNS Query",
                "verbose_name_plural": "DNS Queries",
                "db_table": "customer_eggs_eggrecords_general_models_dnsquery",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EggRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subDomain",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "domainname",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("alive", models.BooleanField(db_index=True, default=True)),
                ("skipScan", models.BooleanField(db_index=True, default=False)),
                (
                    "bugsy_priority_score",
                    models.FloatField(blank=True, db_index=True, null=True),
                ),
                ("bugsy_curation_metadata", models.JSONField(blank=True, null=True)),
                ("bugsy_last_curated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Egg Record",
                "verbose_name_plural": "Egg Records",
                "db_table": "customer_eggs_eggrecords_general_models_eggrecord",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Eggs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "domainname",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Eggs",
                "verbose_name_plural": "Eggs",
                "db_table": "customer_eggs_eggrecords_general_models_eggs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HTTPRequestResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("egg_record_id", models.UUIDField(db_index=True)),
                (
                    "request_url",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("request_headers", models.JSONField(blank=True, null=True)),
                ("request_body", models.TextField(blank=True, null=True)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_headers", models.JSONField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "HTTP Request Response",
                "verbose_name_plural": "HTTP Request Responses",
                "db_table": "customer_eggs_eggrecords_general_models_httprequestresponse",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Nmap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("md5", models.CharField(max_length=255)),
                ("target", models.CharField(max_length=255)),
                (
                    "scan_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("scan_stage", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "scan_status",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "port",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "service_version",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("open_ports", models.TextField(blank=True, null=True)),
                ("scan_command", models.TextField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("hostname", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                (
                    "record_id_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Nmap Scan",
                "verbose_name_plural": "Nmap Scans",
                "db_table": "customer_eggs_eggrecords_general_models_nmap",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NucleiTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_id",
                    models.CharField(db_index=True, max_length=500, unique=True),
                ),
                ("template_path", models.CharField(max_length=1000)),
                (
                    "template_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "cve_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "technology",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                ("tags", models.JSONField(default=list)),
                (
                    "severity",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("reference", models.TextField(blank=True, null=True)),
                (
                    "classification",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("raw_content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Nuclei Template",
                "verbose_name_plural": "Nuclei Templates",
                "db_table": "enrichment_system_nucleitemplate",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PayloadMutation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("template_id", models.BigIntegerField(db_index=True)),
                ("mutated_payload", models.TextField()),
                (
                    "mutated_payload_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("mutation_type", models.CharField(db_index=True, max_length=50)),
                ("mutation_description", models.TextField(blank=True, null=True)),
                ("mutation_details", models.JSONField(blank=True, null=True)),
                (
                    "escape_method_applied",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "escape_method_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("escape_method_details", models.JSONField(blank=True, null=True)),
                ("target_url", models.TextField(blank=True, null=True)),
                (
                    "target_environment",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                ("target_waf", models.CharField(blank=True, max_length=100, null=True)),
                ("target_tech_stack", models.JSONField(blank=True, null=True)),
                ("generation_tools", models.JSONField(blank=True, null=True)),
                ("testing_tools", models.JSONField(blank=True, null=True)),
                (
                    "effectiveness_score",
                    models.FloatField(
                        blank=True, db_index=True, default=0.0, null=True
                    ),
                ),
                ("usage_count", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "success_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "failure_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "ai_confidence",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("is_successful", models.BooleanField(db_index=True, default=False)),
                ("exploitation_verified", models.BooleanField(default=False)),
                ("sabrina_approved", models.BooleanField(default=False)),
                ("parent_mutation_id", models.BigIntegerField(blank=True, null=True)),
                ("mutation_depth", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("first_exploitation_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Payload Mutation",
                "verbose_name_plural": "Payload Mutations",
                "db_table": "customer_eggs_eggrecords_general_models_payloadmutation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RequestMetaData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "record_id_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("request_id", models.CharField(max_length=255)),
                ("session_id", models.CharField(max_length=255)),
                ("target_url", models.CharField(max_length=2048)),
                ("request_method", models.CharField(max_length=10)),
                ("request_headers", models.JSONField(default=dict)),
                ("request_body", models.TextField(blank=True, null=True)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_headers", models.JSONField(default=dict)),
                ("response_body", models.TextField(blank=True, null=True)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                ("user_agent", models.CharField(max_length=255)),
                ("referer", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Request Metadata",
                "verbose_name_plural": "Request Metadata",
                "db_table": "customer_eggs_eggrecords_general_models_requestmetadata",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RyuAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("record_id_id", models.UUIDField(db_index=True)),
                ("risk_level", models.CharField(db_index=True, max_length=50)),
                ("threat_summary", models.TextField(blank=True, null=True)),
                ("vulnerabilities", models.JSONField(blank=True, null=True)),
                ("attack_vectors", models.JSONField(blank=True, null=True)),
                ("remediation_priorities", models.JSONField(blank=True, null=True)),
                ("narrative", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ryu Assessment",
                "verbose_name_plural": "Ryu Assessments",
                "db_table": "customer_eggs_eggrecords_general_models_jadeassessment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SecurityPayload",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("payload", models.TextField()),
                (
                    "payload_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "payload_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("source_file_path", models.TextField(blank=True, null=True)),
                (
                    "source_category",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("source_url", models.CharField(blank=True, max_length=500, null=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("bypass_techniques", models.JSONField(blank=True, null=True)),
                ("target_technology", models.JSONField(blank=True, null=True)),
                ("encoding_methods", models.JSONField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, null=True)),
                (
                    "effectiveness_score",
                    models.FloatField(
                        blank=True, db_index=True, default=0.0, null=True
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        blank=True, db_index=True, default=0, null=True
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "failure_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "ai_confidence",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("is_template", models.BooleanField(db_index=True, default=True)),
                ("has_been_mutated", models.BooleanField(db_index=True, default=False)),
                (
                    "likely_ineffective",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("sabrina_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Security Payload",
                "verbose_name_plural": "Security Payloads",
                "db_table": "customer_eggs_eggrecords_general_models_securitypayload",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TechnologyFingerprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("egg_record_id", models.UUIDField(db_index=True)),
                (
                    "nmap_scan_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "request_metadata_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("technology_name", models.CharField(db_index=True, max_length=255)),
                (
                    "technology_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "technology_category",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("confidence_score", models.FloatField(db_index=True, default=0.0)),
                (
                    "detection_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("raw_detection_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Technology Fingerprint",
                "verbose_name_plural": "Technology Fingerprints",
                "db_table": "enrichment_system_technologyfingerprint",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["egg_record_id"], name="enrichment__egg_rec_6ecdfa_idx"
                    ),
                    models.Index(
                        fields=["technology_name"],
                        name="enrichment__technol_5021cf_idx",
                    ),
                    models.Index(
                        fields=["technology_category"],
                        name="enrichment__technol_0941ff_idx",
                    ),
                    models.Index(
                        fields=["confidence_score"],
                        name="enrichment__confide_f835b0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DirectoryEnumerationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("egg_record_id", models.UUIDField(db_index=True)),
                ("discovered_path", models.CharField(db_index=True, max_length=2048)),
                (
                    "path_status_code",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("path_content_length", models.IntegerField(blank=True, null=True)),
                (
                    "path_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("path_response_time_ms", models.FloatField(blank=True, null=True)),
                (
                    "nmap_scan_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "correlated_port",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "correlated_service_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "correlated_service_version",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "correlated_product",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("correlated_os_details", models.JSONField(blank=True, null=True)),
                ("correlated_cpe", models.JSONField(blank=True, null=True)),
                (
                    "technology_fingerprint_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "detected_cms",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "detected_cms_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "detected_framework",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "detected_framework_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cms_detection_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cms_detection_confidence",
                    models.FloatField(
                        blank=True, db_index=True, default=0.0, null=True
                    ),
                ),
                ("cms_detection_signatures", models.JSONField(blank=True, null=True)),
                ("priority_score", models.FloatField(db_index=True, default=0.0)),
                ("priority_factors", models.JSONField(blank=True, null=True)),
                (
                    "request_metadata_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("correlated_headers", models.JSONField(blank=True, null=True)),
                ("correlated_html_entities", models.JSONField(blank=True, null=True)),
                (
                    "enumeration_tool",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "wordlist_used",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "enumeration_depth",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                ("discovered_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Directory Enumeration Result",
                "verbose_name_plural": "Directory Enumeration Results",
                "db_table": "customer_eggs_eggrecords_general_models_directoryenumerationresult",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["egg_record_id"], name="customer_eg_egg_rec_c967c6_idx"
                    ),
                    models.Index(
                        fields=["discovered_path"],
                        name="customer_eg_discove_e2ef66_idx",
                    ),
                    models.Index(
                        fields=["path_status_code"],
                        name="customer_eg_path_st_90f078_idx",
                    ),
                    models.Index(
                        fields=["priority_score"], name="customer_eg_priorit_324159_idx"
                    ),
                    models.Index(
                        fields=["detected_cms"], name="customer_eg_detecte_651851_idx"
                    ),
                    models.Index(
                        fields=["correlated_port"],
                        name="customer_eg_correla_457500_idx",
                    ),
                    models.Index(
                        fields=["egg_record_id", "priority_score"],
                        name="customer_eg_egg_rec_79443c_idx",
                    ),
                    models.Index(
                        fields=["egg_record_id", "detected_cms"],
                        name="customer_eg_egg_rec_890440_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CVEFingerprintMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("egg_record_id", models.UUIDField(db_index=True)),
                (
                    "technology_fingerprint_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("cve_id", models.CharField(db_index=True, max_length=50)),
                (
                    "cve_severity",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "cve_cvss_score",
                    models.FloatField(blank=True, db_index=True, null=True),
                ),
                (
                    "technology_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("match_confidence", models.FloatField(db_index=True, default=0.0)),
                (
                    "nuclei_template_available",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "nuclei_template_ids",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "recommended_for_scanning",
                    models.BooleanField(db_index=True, default=True),
                ),
                ("bugsy_confidence_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "CVE Fingerprint Match",
                "verbose_name_plural": "CVE Fingerprint Matches",
                "db_table": "enrichment_system_cvefingerprintmatch",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["egg_record_id"], name="enrichment__egg_rec_503e44_idx"
                    ),
                    models.Index(
                        fields=["technology_fingerprint_id"],
                        name="enrichment__technol_b80b46_idx",
                    ),
                    models.Index(
                        fields=["cve_id"], name="enrichment__cve_id_d6ca3d_idx"
                    ),
                    models.Index(
                        fields=["cve_severity"], name="enrichment__cve_sev_bdd5d8_idx"
                    ),
                    models.Index(
                        fields=["cve_cvss_score"], name="enrichment__cve_cvs_400e20_idx"
                    ),
                    models.Index(
                        fields=["match_confidence"],
                        name="enrichment__match_c_98bfec_idx",
                    ),
                    models.Index(
                        fields=["recommended_for_scanning"],
                        name="enrichment__recomme_364284_idx",
                    ),
                    models.Index(
                        fields=["nuclei_template_available"],
                        name="enrichment__nuclei__ce75f7_idx",
                    ),
                ],
            },
        ),
    ]
