/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "nuclei_bridge.go"


#include <stdlib.h>
#include "nuclei_bridge.h"

// Callback function types - Python will provide these function pointers
typedef void (*VulnCallback)(char* jsonData);
typedef void (*ProgressCallback)(char* jsonData);
typedef void (*StateCallback)(char* jsonData);
typedef void (*ErrorCallback)(char* jsonData);

// Helper functions to call callbacks from Go
static inline void call_vuln_callback(VulnCallback cb, char* data) {
    if (cb != NULL) cb(data);
}
static inline void call_progress_callback(ProgressCallback cb, char* data) {
    if (cb != NULL) cb(data);
}
static inline void call_state_callback(StateCallback cb, char* data) {
    if (cb != NULL) cb(data);
}
static inline void call_error_callback(ErrorCallback cb, char* data) {
    if (cb != NULL) cb(data);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* InitializeNucleiEngine(char* engineID, char* configJSON, int useThreadSafe);
extern char* RegisterCallbacks(char* engineID, char* scanID, VulnCallback vulnCB, ProgressCallback progressCB, StateCallback stateCB, ErrorCallback errorCB);
extern char* ExecuteScan(char* engineID, char* targetsJSON);
extern char* GetScanState(char* engineID);
extern char* PauseScan(char* engineID);
extern char* ResumeScan(char* engineID);
extern char* AdjustRateLimit(char* engineID, int rateLimit);
extern char* CloseEngine(char* engineID);

#ifdef __cplusplus
}
#endif
